### PR TITLE
Allow self-signed certificates

### PR DESCRIPTION
**Pull request by homeyjd**

### CODE REVIEW

**Comment by itay** [comment]
@homeyjd thanks for sending this and submitting the Contribution Agreement. I'm curious, which version of PHP did you run into the issue with?

**Comment by homeyjd** [comment]
5.6.
Was working fine on 5.4. Recently updated to 5.6.15 and it broke.

**Comment by homeyjd** [comment]
We'd be open to an option of "allow_selfsigned" in the config hash passed to new Splunk_Service($conf).
As it stands it appears the only way to use the stream_context HTTP transport class AND allow self-signed certs is code change.

I saw CURLOPT_SSL_VERIFYPEER => false in Http::requestWithCurl(), but I can't trigger that functionality directly.  The only alternative was to re-implement the HTTP transport class, and that seemed silly considering the fix was so small.

**Comment by itay** [comment]
Yep - it looks like the default changed in 5.6: http://php.net/manual/en/migration56.openssl.php

An option would be nice, but I think the change is OK as is, given that it was basically defaulted to `false` anyway. Let me know if you want to change this to add an option.

**Comment by homeyjd** [comment]
An option would be cool, but the quick fix works for us now.

fwiw, I saw you had pulled a PR for adding Composer integration.  Would love to get the autoloading pushed upstream.  You're instructions for contributing only allow submitting a PR against a single branch.  Can I add this commit to this PR?
https://github.com/dmvorg/splunk-sdk-php/commit/b893736f0882c96559ef3986e21cefe6e122093b

Composer uses master-branch for parsing the package name, so the integration won't be complete until merged to master.  But our fork is working well with Composer:
```json
{
  "repositories": [
        { "type": "vcs", "url": "https://github.com/dmvorg/splunk-sdk-php" }
  ],
  "require": {
    "splunk/splunk-sdk-php": "dev-master"
  }
}
```

**Comment by adamziaja** [comment]
https://github.com/splunk/splunk-sdk-php/pull/40/commits

**Comment by shakeelmohamed** [comment]
We've merged #41 instead, thanks everyone.

**Pull request closed without merging**
